crate/crash

- CHANGES.txt
- LICENSE
- NOTICE
- setup.py
- src/crate/crash/command.py
- src/crate/crash/crash.txt
- src/crate/crash/test_command.py
- src/crate/crash/tests.py
- versions.cfg
- raw json output
- json output that maps column name
- coloured output for interactive usage
> added output format options

- CHANGES.txt
- buildout.cfg
- docs/cli.txt
- docs/formats.txt
- docs/index.txt
- docs/usage.txt
- setup.py
- src/crate/crash/command.py
- src/crate/crash/printer.py
- src/crate/crash/test_command.py
- src/crate/crash/tests.py
- src/crate/crash/usage.txt
- tox.ini
- versions.cfg
this new cli implementation uses https://github.com/jonathanslenders/python-prompt-toolkit
additionally crash commands and output formatting were added
> alternative cli implementation using prompt toolkit

- CHANGES.txt
- setup.py
- src/crate/crash/command.py
> support argcomplete if available

- CHANGES.txt
- src/crate/crash/tabulate.py
- src/crate/crash/test_command.py
based on https://bitbucket.org/astanin/python-tabulate/issues/28/feature-request-multiline-cells-and
> added multiline support for tabular output format

- CHANGES.txt
- docs/cli.txt
- docs/formats.txt
- src/crate/crash/outputs.py
- src/crate/crash/test_command.py
prints a json dataset row-by-row in separate lines
> added json_row output format

- bootstrap.py
wasn't able to run `python bootstrap.py` on windows with the old file.
> update bootstrap file

- setup.py
- versions.cfg
Contains some bug fixes and performance improvements.
> update prompt-toolkit to 0.59

- .travis.yml
- CHANGES.txt
- README.rst
- setup.py
- src/crate/crash/test_command.py
- tox.ini
Dropped python 2.6 support in crate-python
> drop python 2.6 support

- CHANGES.txt
- src/crate/crash/commands.py
- src/crate/crash/test_commands.py
> fixed read file command for legacy python

- CHANGES.txt
- devtools/bundle.py
> declare utf-8 encoding in crash_standalone

- docs/cli.txt
- src/crate/crash/commands.py
- src/crate/crash/output.txt
- src/crate/crash/test_command.py
- src/crate/crash/test_commands.py
- src/crate/crash/usage.txt
> rename the argument of the check command

- CHANGES.txt
- src/crate/crash/command.py
Please enter the commit message for your changes. Lines starting
> removed listing of 'pg_catalog' in \dt sql query

- CHANGES.txt
- setup.py
@mfussenegger  please take a look
jürgen reported that issue
> require pygments >= 2.0

- CHANGES.txt
- src/crate/crash/repl.py
> updated autocompletion to reflect newest crate

- CHANGES.txt
c5abb4e8b3f91202afcbab74acfe3fcc1dc8ebf0
> added missing metadata query changelog

- src/crate/crash/usage.txt
c5abb4e8b3f91202afcbab74acfe3fcc1dc8ebf0
@mfussenegger pls take a 👀
> update limitation to reflect change in Information Schema

- src/crate/crash/repl.py
- src/crate/crash/test_repl.py
> Fixed unusual capitalisation behaviour

- CONTRIBUTING.rst
slightly more idiomatic wording I think
> fix wording

- CHANGES.txt
- src/crate/crash/command.py
- src/crate/crash/commands.py
- src/crate/crash/test_commands.py
Fixes https://github.com/crate/crash/issues/210
> Verbose command didn't propery add/remove the ?error_trace http param

- src/crate/crash/repl.py
Adds support for indentation via tab. Only works in multi-line:
The following does nothing:
```
<tab>
```
This works:
```
create table t1 x (
<tab> -> 4 spaces
```
De-indentation:
```
create table t1 x(
<bs> -> removes 4 spaces
```
In addition the auto-completion popup is only shown if at least 1 character has been typed.
> Add support for tab indentation & backspace de-indentation

- src/crate/crash/repl.py
> changed toolbar key color to `cyan`

- CHANGES.txt
- src/crate/crash/tabulate.py
This broke the `itest` with Crate 2.2
> revert multiline header feature

- CHANGES.txt
- src/crate/crash/command.py
- src/crate/crash/test_command.py
- src/crate/crash/tests.py
> Support pasting of multiple statements

- src/crate/crash/command.py
Broke with 343945b6d66a95ddeab3573bc7a9e14c49da04fa
> Fix stdin handling

- CHANGES.txt
this should make changelog handling easier when reflecting releases on master changelog
> introduced changes and fixes in "unreleased" section of changelog

- .travis.yml
> clean virtualenv on travis to avoid dependency problems

- docs/compatibility.txt
- docs/index.txt
collecting both on one pr for less notification noise
> minor docs changes

- src/crate/crash/test_keybinding.py
that have been created by <TAB>
> add <BACKSPACE> key binding test

- src/crate/crash/command.py
- src/crate/crash/test_command.py
Closing a CrateShell object releases open cursors and connections.
Additionally, the CrateShell class also implements the `__enter__` and
`__exit__` methods of the context manager. This means it can used in
conjunction with the `with` statement:
```python
with CrateShell(['localhost:4200'], error_trace=True) as crash:
...
```
> make CrateShell objects closable

- CHANGES.txt
add missing changelog entry for  #272
> add changelog entry for commit #8e7f7e9

- README.rst
- docs/appendices/compatibility.txt
- docs/getting-started.txt
- docs/run.txt
for https://trello.com/c/7bdvVTnH/3505
> update install docs

- .travis.yml
> Bump Travis CI to use OpenJRE 11

- src/crate/crash/command.py
- src/crate/crash/test_command.py
> Minor test cleanups

- docs/appendices/compatibility.txt
- docs/appendices/formats.txt
- docs/appendices/index.txt
- docs/getting-started.txt
- docs/index.txt
- docs/run.txt
Change directive headings and page titles to sentence case capitalization
> Change directive headings and page titles to sentence case capitalization

- docs/appendices/compatibility.rst
- docs/appendices/formats.rst
- docs/getting-started.rst
- docs/run.rst
see https://github.com/crate/tech-writing-domain/issues/336
> Fix broken and redirected links (as reported by sphinx-build -b linkcheck)

- docs/_extra/robots.txt
This fixes the "Sitemap" value in `robots.txt`.
> Fix "Sitemap" value in robots.txt

- .github/workflows/main.yml
- CHANGES.txt
- setup.py
- tox.ini
> Added support for Python 3.9

- README.rst
> Add more badges to the README

- LICENSE
This patch removes some old cruft from the LICENSE file.
> Clean up LICENSE file

- CHANGES.txt
- crate/crash/__init__.py
What the title says: We would like to bring the recent updates to PyPI.
> Prepare release 0.27.0

- .mergify.yml
if you don't specify both tests, mergify will merge when the first one passes
> Specify both docs tests

- .github/workflows/main.yml
- CHANGES.txt
- setup.py
- tox.ini
> Added support for Python 3.10

- crate/crash/repl.py
- setup.py
In the same spirit as the other recent patches, this one updates the `prompt-toolkit` dependency package. It will resolve GH-338.
> Dependencies: Update to prompt-toolkit v3

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/main.yml
- .gitignore
- CHANGES.txt
- DEVELOP.rst
- crate/crash/command.py
- crate/crash/commands.py
- crate/crash/sysinfo.py
- setup.py
- tests/test_command.py
- tests/test_commands.py
- tests/test_integration.py
- tests/test_sysinfo.py
> Chore: Update versions across the board for CI and sandbox

- CHANGES.txt
- DEVELOP.rst
- crate/crash/__init__.py
Running a release with an important fix.
- GH-380
> Release 0.29.0

- DEVELOP.rst
I found a little typo while setting up the project. :smile:
> Documentation: fix typo in DEVELOP.rst

- .github/workflows/codeql.yml
- .github/workflows/main.yml
- crate/crash/tabulate.py
The code scanning alert https://github.com/crate/crash/security/code-scanning/30 has been created two weeks ago.
> Fix CodeQL code scanning admonition about invalid comparison operand

- .github/workflows/main.yml
Update CI configuration to use most recent version of CrateDB.
> CI: Update to CrateDB 5.3.2

- .github/dependabot.yml
Adding a Dependabot configuration file to help maintaining dependencies.
> CI: Add Dependabot configuration

- .github/workflows/main.yml
- DEVELOP.rst
- devtools/ci.sh
> Documentation: add info about CI pipeline steps to developing guide

- CHANGES.txt
- crate/crash/__init__.py
In order to ship the improvements from GH-386 by @JustBeYou.
> Release 0.30.0

- .readthedocs.yml
- DEVELOP.rst
- README.rst
- CI: Add configuration file for Read the Docs, it becomes mandatory
- Chore: Update documentation
> CI: Fix RTD build, and minor documentation updates

- .github/workflows/codeql.yml
- .github/workflows/docs.yml
- .github/workflows/main.yml
Just a small maintenance patch to synchronize CI configuration between software tests, quality checks, and documentation builds, also configuring them as nightly jobs for continuous monitoring.
> CI: Adjust scheduling configuration

- docs/run.rst
Tested locally, should just work™
> Add lazyload to image

- .github/workflows/main.yml
- setup.py
Update CI configuration to include Python 3.13.
> CI: Verify support on Python 3.13
