crate/crash

setup.py

otherwise install via pip won't work

nail versions for prompt-toolkit and jedi

---

CHANGES.txt
src/crate/crash/command.py

that caused warning logs from the crate-python library being
printed to stderr

fixed misconfigured logging

---

src/crate/crash/usage.txt

because pypy does not allow any references in the readme

made link instead of reference in usage docs

---

CHANGES.txt
src/crate/crash/command.py

In python3 TypeError doesn't have a message attribute.

fix py3 exception logging error

---

CHANGES.txt
src/crate/crash/outputs.py

E.g.
select x, y
Results in
{
"x",
"y"
}
And
select y, x
results in
{
"y",
"x"
}
Instead of having a random order

json output: order keys by the select list

---

src/crate/crash/command.py
src/crate/crash/repl.py

Catching KeyboardInterrupt in the CrateCmd makes it impossible to
interrupt processes that use the CrateCmd class (Like the doctests in
Crate do)
This commit moves the KeyboardInterrupt handling into the repl module so
that it will only be caught if crash is used interactively. (That was
the original intention when it was added.)

move KeyboardInterrupt handling into repl

---

setup.py
src/crate/crash/command.py
src/crate/crash/repl.py

Includes a lot of of VI mode improvements!
And the following change makes our `get_height` override unnecessary:
- Only reserve menu space when `complete_while_typing=True` or when
there are completions to be displayed.

Update prompt-toolkit to 1.0.0

---

docs/cli.txt

In Crate 0.55 the DELETE statements will have a rowcount (unless it's
done on a partitioned table and partitions are removed)

Remove note about DELETE rowcount

---

CHANGES.txt
src/crate/crash/command.py
src/crate/crash/test_command.py

e.g.
* `:` for <default_host>:<default_port> -> `localhost:4200`
* `:4321` for `<default_host>:4321` -> `localhost:4321`
* `crate1.example.com` for  `crate1.example.com:<default_port>` -> `crate1.example.com:4200`

allow short hosts

---

CHANGES.txt
src/crate/crash/command.py
src/crate/crash/config.py
src/crate/crash/test_config.py

if no hosts were provided via `--hosts` argument and configuration file was already present

crash was trying to connect to invalid hosts

---

CHANGES.txt
src/crate/crash/outputs.py
src/crate/crash/test_command.py

happened when node name contains unicode character such as umlaut
Error message was:
```
Traceback (most recent call last):
File "bin/crash", line 24, in <module>
sys.exit(crate.crash.command.main())
File "/Users/christian/sandbox/crate/crash/src/crate/crash/command.py", line 429, in main
cmd.sys_info_cmd.execute()
File "/Users/christian/sandbox/crate/crash/src/crate/crash/sysinfo.py", line 93, in execute
self.cmd.pprint(result.rows, result.cols)
File "/Users/christian/sandbox/crate/crash/src/crate/crash/command.py", line 217, in pprint
self.output_writer.write(result)
File "/Users/christian/sandbox/crate/crash/src/crate/crash/outputs.py", line 94, in write
for line in output:
File "/Users/christian/sandbox/crate/crash/src/crate/crash/outputs.py", line 123, in mixed
val = …
```

fixed unicode error in --sysinfo command

---

src/crate/crash/command.py
src/crate/crash/test_commands.py
src/crate/crash/tests.py

this is a fix for https://github.com/crate/crash/commit/c5abb4e8b3f91202afcbab74acfe3fcc1dc8ebf0 which is not yet released and therefore has no changelog entry

\dt command now also works when connecting to a CrateDB version < 0.57.0

---

versions.cfg

solves `ERROR: unknown environment 'py35' ` when running bin/tox on jenkins

versions: tox and prompt-toolkit

---

CHANGES.txt
docs/cli.txt
src/crate/crash/command.py
src/crate/crash/commands.py
src/crate/crash/repl.py
src/crate/crash/test_command.py
src/crate/crash/test_commands.py
src/crate/crash/test_repl.py
src/crate/crash/tests.py

auto-capitalize keywords while typing

---

src/crate/crash/repl.py

- fixed the cursor issue http://g.recordit.co/I5kZVj8LQK.gif
- fixed when you type `select * from foo` then move the cursor back to `*` and add `date_trunc` it will capitalize DATE but not lowercase it again when typing further. http://g.recordit.co/hTB7BCuB0C.gif

fixed autocapitalize cursor issue

---

CHANGES.txt
src/crate/crash/command.py
src/crate/crash/test_command.py
src/crate/crash/tests.py

```
cr> BEGIN;
Traceback (most recent call last):
File "/mnt/c/Users/mibe/bin/crash", line 24, in <module>
sys.exit(crate.crash.command.main())
File "/mnt/d/sandbox/crate/crash/src/crate/crash/command.py", line 464, in main
loop(cmd, args.history)
File "/mnt/d/sandbox/crate/crash/src/crate/crash/repl.py", line 312, in loop
cmd.process(doc.text)
File "/mnt/d/sandbox/crate/crash/src/crate/crash/command.py", line 242, in process
self._exec(line)
File "/mnt/d/sandbox/crate/crash/src/crate/crash/command.py", line 333, in _exec
success = self.execute(line)
File "/mnt/d/sandbox/crate/crash/src/crate/crash/command.py", line 354, in execute
command = statement[:re.search("\s", statement).start()].upper()
AttributeError: 'NoneType' object has no attribute 'start'
```

fixed single word statement printing

---

CHANGES.txt
src/crate/crash/command.py

It now looks like that:
```
➭ bin/crash -v --verify-ssl true --cert-file /tmp/certs/marios.crt --key-file /tmp/certs/marios.key --ca-cert-file /tmp/certs/rootCA.crt --hosts https://127.0.0.1:4200 -U unknonwn
/Users/matriv/crate/crash/eggs/urllib3-1.14-py3.6.egg/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for 127.0.0.1 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)`
SubjectAltNameWarning
401 Client Error: Unauthorized
```

Don't print the whole stack trace on Connection error.

---

CHANGES.txt
src/crate/crash/repl.py

start autocompletion for non-command keys at the 3rd character

---

CHANGES.txt
src/crate/crash/tabulate.py

```
cr> select 1 = (select 2);
+----------------+
| (1 = (SELECT 2 |
|                |
| ))             |
+----------------+
| FALSE          |
+----------------+
SELECT 1 row in set (0.003 sec)
cr>
```

added support for multiline table headers in the tabular output format

---

CHANGES.txt
src/crate/crash/command.py
src/crate/crash/layout.py
src/crate/crash/repl.py
src/crate/crash/sysinfo.py
src/crate/crash/test_repl.py
src/crate/crash/tests.py

* shows the current session user
* shows the handler nodes connected with

added session toolbar

---

CHANGES.txt
src/crate/crash/tabulate.py
src/crate/crash/test_command.py

fixed the problem with the formatting if the first row was empty, in line 585 & 586
also added some formatting tests

crash multiline header fix

---

CHANGES.txt
src/crate/crash/command.py

this does not require to connect twice on startup any more

show connect message only in verbose mode

---

src/crate/crash/command.py

A file with trailing whitespace could lead to something like this:
CONNECT OK
DROP OK, 1 row affected  (0.058 sec)
CREATE OK, 1 row affected  (0.193 sec)
SQLActionException[Failed to parse source [{"stmt": ""}]]

Don't execute lines containing only whitespaces

---

docs/cli.txt

Which stated CRASHPW instead of CRATEPW.

Fixed wrong example in environment variables documentation

---

src/crate/crash/command.py
src/crate/crash/test_command.py
src/crate/crash/test_commands.py
src/crate/crash/test_repl.py
src/crate/crash/test_sysinfo.py
src/crate/crash/tests.py

rename CrateCmd to CrateShell

---

setup.py

If `crate` `0.21` is already installed it is not updated, resulting in
an error that `connect` has no argument `schema`.

Bump crate version requirement for schema support

---

docs/getting-started.txt
docs/index.txt

I just added a new set of styles for admonitions in the docs. I am now going through each docs project and improving our use of admonitions
the "formats" removal was to fix a build error necessary to make these changes

improve use of admonitions

---

devtools/bundle.py

The shebang `/usr/bin/env python` may execute the bundle with Python 2
which leads to a import error later in the code execution:
```console
$ ./crash_standalone_latest
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "./crash_standalone_latest/__main__.py", line 11, in <module>
File "./crash_standalone_latest/crate/crash/command.py", line 36, in <module>
File "./crash_standalone_latest/crate/client/__init__.py", line 22, in <module>
File "./crash_standalone_latest/crate/client/connection.py", line 24, in <module>
File "./crash_standalone_latest/crate/client/http.py", line 39, in <module>
ImportError: No module …
```

require python3 in standalone bundle

---

CHANGES.txt
src/crate/crash/command.py

Removing newlines has some unwanted side effects like line comments not
terminating at the end of the line anymore.

Preserve newlines to be able to support line comments properly

---

docs/appendices/compatibility.txt
docs/getting-started.txt
docs/run.txt

Changes headers from title case to sentence case.

changes headers to sentence case

---

setup.cfg
src/crate/crash/command.py

This adds true/false as explicit choices so that the help output is a
bit friendlier.
[--verify-ssl {True,False}]
--verify-ssl {True,False}
Enable or disable the verification of the server SSL
certificate
In CLIs with boolean flags it is also sometimes the case that you've a
``--no-*`` variant or that you can use ``no`` or something like that. So
having to pass ``false`` is not necessarily intuitive.

Make --verify-ssl choices explicit

---

src/crate/crash/command.py

Since we no longer support Python < 3.1 it can be removed
The NullHandler exists since Python 3.1
(https://docs.python.org/3/library/logging.handlers.html?highlight=nullhandler#nullhandler)

Remove NullHandler fallback logic

---

src/crate/crash/repl.py

If you're writing a query and hit `Ctrl+c` it now resets the input
buffer, so that you can start over.

Reset the buffer on Ctrl+c

---

.travis.yml
CHANGES.txt
README.rst
setup.py
tox.ini

Some of the newer versions of our dependencies dropped support for
Python 3.4.
Python 3.4 has reached end of life and according to
https://en.wikipedia.org/wiki/CPython#Enterprise_Linux only Debian 8
shipped Python 3.4 to begin with.

Drop Python 3.4 support

---

CHANGES.txt
crate/crash/repl.py
setup.py

This commit changes the lexer for tokenizing the user input from the
generic SqlLexer to the more specific PostgresLexer.
Additionally the color scheme has been changed from a custom on to
"terminal style", meaning that it will pick up the colors of the
terminal emulator (http://pygments.org/docs/styles/#ansiterminalstyle).

Improve visual representation of SQL statements

---

.travis.yml
crate/crash/command.py
crate/crash/commands.py
crate/crash/config.py
crate/crash/keybinding.py
crate/crash/layout.py
crate/crash/outputs.py
crate/crash/printer.py
crate/crash/repl.py
crate/crash/sysinfo.py
crate/crash/tabulate.py
setup.cfg
setup.py
tests/test_command.py
tests/test_commands.py
tests/test_config.py
tests/test_integration.py
tests/test_keybinding.py
tests/test_repl.py
tests/test_sysinfo.py

Using [`isort`](https://pypi.org/project/isort/) for consistent import ordering and formatting.

Apply and enforce isort on codebase

---

CHANGES.txt
crate/crash/command.py
tests/test_commands.py

Sort the output of the `\dt` command alphabetically

---

CHANGES.txt
crate/crash/command.py
crate/crash/repl.py
tests/test_integration.py
tests/test_repl.py

You can see at a glance which cluster you're connected to.

Display cluster name in status line

---

.travis.yml
CHANGES.txt
setup.py
tox.ini

Python 3.8 has been released on Oct 14, 2019
https://www.python.org/dev/peps/pep-0569/#id6

Add official support for Python 3.8

---

CHANGES.txt
crate/crash/repl.py

When in vi-mode, pressing ctrl+r starts the search mode. We would expect
that pressing ctrl+c to close the search mode would return focus back to
the text input, but this never happened.
What was happening is that, when you press ctrl-r, a new control element
is created called a SearchBufferControl, which is then focused on.
Pressing esc closes this control, and returns focus to the previous
control (the one created by our default text buffer).
For some reason, the keyboard interrupt exception isn't caught by this
control, and is instead bubbled up to our application. Consequently,
this SearchBufferControl remains in focus and cannot be escaped.
This PR sets it so that when a KeyboardInterrupt is caught and the
current buffer control is a search buffer control, focus is instead
given back …

Fix ctrl+r search cancelling not returning focus

---

CHANGES.txt
crate/crash/repl.py
tests/test_repl.py

Previously, our list of keywords we highlighted on was hard coded, and not tied to a version of CrateDB. This replaces that list, instead using the list of keywords returned by `pg_get_keywords()`

Dynamically load keywords from pg_get_keywords

---

crate/crash/repl.py

Connecting to a cluster that doesn't have a `pg_get_keywords()` function
looked like:
crash --verify-ssl no --hosts https://localhost:4200 -U crate
CONNECT OK
SQLActionException[SQLParseException: line 1:44: mismatched input '(' expecting {<EOF>, ';'}]

Don't print error if pg_get_keywords is not available

---

.gitignore
DEVELOP.rst
README.rst
docs/Makefile
docs/build.json
docs/docutils.conf
docs/requirements.txt

this PR switches docs build to https://github.com/crate/crate-docs-build

Upgrade docs to use standard crate-docs-build system

---

CHANGES.txt
crate/crash/command.py
setup.py

@chaudum As I understand, the TCP keepalive is enabled by default, so just upgrading the python driver should add it. Do you think it would be worth explicitly setting it to true for clarity's sake?

Upgrade CrateDB python driver to 0.26.0

---

CHANGES.txt
crate/crash/keybinding.py

Hi there,
thanks a bunch for conceiving and maintaining `crash`. 
When starting to work with the program recently, it regularly occurred to me that I unintentionally quit the program by pressing CTRL-D. This improvement only quits the program when pressing CTRL-D on an **empty** command line. Otherwise, CTRL-D will act as the delete key, as we are used to it when working within other shells.
With kind regards,
Andreas.
P.S.: Unfortunately, I haven't been able to invoke the test suite. I hope this change doesn't break anything related to that. Let me know if this update needs any further adjustments.

Make ctrl-d only quit program on empty command line

---

.github/workflows/docs.yml
.gitignore
.mergify.yml
docs/Makefile
docs/build.json

the primary purpose of this is to upgrade to the new docs build system
I noticed that the Travis config was gone but I can't find the commit that removed it. hmm
we currently use Travis for testing the docs. I've added back in a Travis config that only tests the docs
I've also gone ahead and added the Mergify config we're using on other docs projects. but I have slightly modified it to account for the GitHub Actions you have set up for testing the code
lmk what you think!! :)

Upgrade to new docs build 0.4.0

---

docs/run.rst

see crate/tech-writing-domain#316

Correction: Use HTTPS instead of HTTP for links

---

devtools/create_tag.sh

It looks like `create_tag.sh` depended on a local buildout installation beforehand. This improvement by @mfussenegger already appears to get things more straightforward on this matter.
Hereby, I am handing this in as a pull request.

Fix create_tag script

---

setup.py

While everything went through on the last publishing operation for version 0.27.0, this fixes a warning which appeared at the end of the build process.

Fix warning from last publishing operation

---

.github/workflows/main.yml

This removes installing Java on CI/GHA. Because CrateDB now bundles the JRE, this should not do any harm but will save some cycles instead.

CrateDB bundles the JRE with recent releases so we don't need it on CI

---

.github/workflows/docs.yml
.github/workflows/main.yml
.mergify.yml
docs/Makefile
docs/build.json

Hi there,
this is a maintenance patch which does three things.
- Update documentation builder subsystem to the most recent version
- Bump some versions of recipes within the CI configuration
- Update the Mergify configuration to the new schema
It was needed to verify configuration changes coming in from https://github.com/crate/crate-docs-theme/pull/328.
With kind regards,
Andreas.

Update documentation subsystem, CI dependencies and Mergify configuration

---

.github/workflows/main.yml
CHANGES.txt
DEVELOP.rst

Releasing 0.28.0 had some troubles because the PyPI token was named differently in the project's settings vs. the CI job configuration. This patch adjusts it to use the standard name `PYPI_API_TOKEN`, as outlined within the corresponding documentation [^1].
Afterwards, two other commits have been added:
- b057d2d adjusts the version of the GHA -> PyPI publish action
- 84fb56c6fe improves the release documentation
[^1]: https://github.com/pypa/gh-action-pypi-publish

Standardize PyPI auth token name on CI and improve release documentation

---

.github/workflows/docs.yml
.github/workflows/main.yml
setup.py
tests/test_integration.py

- Update GHA recipe versions.
- Update CrateDB versions, use 4.8.4 and 5.1.1.
- Add support for Python 3.11.

Chore: CI maintenance

---

.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/main.yml
DEVELOP.rst
README.rst
setup.cfg
setup.py
tests/test_integration.py

Hi there,
this patch does not change too much, but accomodates the update to `isort5` with 7fb303c, and protects against major version bumps of dependency packages with 85ac5d989f.
While trying to make CI succeed, the CodeQL configuration had to be adjusted (844942b, 54d5882), and, while being at it, 7dff1e8 has been added to save resources when quickly pushing to CI consecutively.
With kind regards,
Andreas.

Chore: Regular maintenance updates

---

.mergify.yml

The Mergify configuration used the deprecated `rebase_fallback` mode of the queue and/or merge action.
- https://docs.mergify.com/actions/queue/#queue-action
- https://github.com/crate/crash/pull/376/checks

Chore: Fix Mergify configuration

---

.github/workflows/main.yml
CHANGES.txt
README.rst
crate/crash/tabulate.py
setup.py

In the spirit of modernizing the package dependencies, in order to allow the program to co-exist within Python environments needing a more recent version of the `tabulate` package, this patch uses the gist of https://github.com/astanin/python-tabulate/pull/161 to accomodate the update.
~~P.S.: While that patch to `tabulate` officially drops support for Python 3.6, the `crash` test suite still succeeds, so why not keep it for a while.~~
Following that patch to `tabulate`, this patch implicitly drops support for Python 3.6 here. Nevertheless, we will state it within the changelog explicitly.

Dependencies: Update to tabulate 0.9.0, and drop support for Python 3.5 and 3.6

---

README.rst
crate/crash/command.py
setup.py

The `appdirs` library stopped being maintained, and `platformdirs`, a friendly fork, is the official successor library.
- https://pypi.org/project/appdirs/
- https://pypi.org/project/platformdirs/

Dependencies: Switch from `appdirs` to `platformdirs`

---

CHANGES.txt
crate/crash/command.py
crate/crash/commands.py
crate/crash/sysinfo.py
setup.py
tests/test_command.py
tests/test_commands.py
tests/test_sysinfo.py

This patch fixes a compatibility issue with the recently released `crate-0.30.0` package, reported by @proddata. Thanks! It is related to: 
- https://github.com/crate/crate-python/pull/513
```python
File "/var/lib/jenkins/workspace/CrateDB/crate_test_hourly_master/blackbox/.venv/lib/python3.9/site-packages/crate/crash/command.py", line 401, in _fetch_session_info
and self.connection.lowest_server_version >= StrictVersion("2.0"):
TypeError: '>=' not supported between instances of 'Version' and 'StrictVersion'
```

Fix compatibility issue with `crate-0.30.0` when comparing versions

---

.github/workflows/main.yml
DEVELOP.rst

I found the CI to be rather heavy, it takes ages to complete. This patch makes it a bit more lightweight, following practises we already applied to other repositories successfully [1], without ending up missing any incompatibility issues so far.
- ~~Take CrateDB 4.8 release out of the test matrix.~~
- Run only a single test matrix slot for macOS and Windows, using the most recent stable Python 3.11. I think it is acceptable.
- [1] https://github.com/earthobservations/wetterdienst/pull/817

CI: Reduce resource usage and speed up testing cycle

---

.github/workflows/codeql.yml
.github/workflows/main.yml

GH-386 revealed that software tests apparently are not invoked on pull requests. This patch aims to improve that detail.

CI: Run software tests on pull requests

---

.github/workflows/main.yml
CHANGES.txt
crate/crash/command.py

This patch aims to fix GH-384 reported by @hammerhead.
> For some types of statements, there have been two spaces between the message (1 row affected) and the runtime (0.172 sec) instead of one.

Fix inconsistent spacing around printed runtime

---

tests/test_commands.py

@seut discovered we did not have a single test case using SQL comments. This patch adds two corresponding test cases.

Tests: Add test cases using comments within SQL and JS statements

---

CHANGES.txt
crate/crash/command.py
setup.py
tests/test_commands.py
tests/test_integration.py

Fixes #349 
As discussed in the issue, I replaced the custom SQL parsing with `sqlparse` library as it seems to be more reliable. Also, I saw there is an inconsistency between `process` and `process_iterable` as one was able to execute commands and the other did not, so I refactored how they work a little.
Now, multi-line input can contain single-line SQL, multi-line SQL and commands, all together.

Add support for multi-line SQL and commands.

---

.github/dependabot.yml
.github/workflows/main.yml
.github/workflows/release.yml

The GHA recipe did not manage to publish a release to PyPI. Because
everything works on the `crate` driver package, let's just use the same
recipe here without further ado.
The GHA recipe did not trigger the »Publish package to PyPI« step.
I did not investigate why.
-- https://github.com/crate/crash/actions/runs/5480636342/jobs/9984067119

CI: Fix staging releases through GitHub Actions

---

.github/workflows/codeql.yml
.github/workflows/docs.yml
.github/workflows/main.yml
.github/workflows/release.yml
setup.py

After https://github.com/jazzband/geojson/pull/222 has been released with geojson 3.1.0, verify that everything works well on Python 3.12, and add it to the package's metadata. Also use it right away on other auxiliary CI tasks.

Add support for Python 3.12

---

.github/workflows/main.yml

On CI, use a more recent version of CrateDB.

CI: Use CrateDB 5.4.5

---

tests/test_integration.py

> Would be great if we could switch to using os/arch related download url's [^1] in future.
>
> -- https://github.com/crate/crate-python/pull/593#issuecomment-1794710816
[^1]: https://cdn.crate.io/downloads/releases/cratedb/x64_linux/
- https://github.com/crate/crate-python/pull/594

Sandbox: Download Linux variant of CrateDB from os/arch-specific URL

---

CHANGES.txt
crate/crash/command.py

Display the list of available output format choices right away within `crash --help`, to improve guidance. Thank you for this suggestion, @mfussenegger, it will resolve GH-409.
```
crash --help
```
[...]
```
--format FORMAT       the output FORMAT of the SQL response. choose one of: tabular,
json, csv, raw, mixed, dynamic, json_row
```

CLI: Display output format choices within `crash --help`

---

.github/workflows/main.yml

This is meant to support GH-408, so that we can get successful outcomes on the Python >= 3.8 slots already.
It is intended to be a temporary change, for a better overview. It can be reverted to save resources on daily operations later.

CI: Turn off failing fast on the test matrix slots

---

docs/build.json
docs/commands.rst
docs/run.rst

There was another patch by @mfussenegger to be able to configure external pager programs.
- GH-418
This patch adds the corresponding documentation for the new feature.
Other than the intended improvement, the PR also includes two other minor fixes/updates within separate commits.
NB: You may also want to review or acknowledge this? /cc @matriv, @seut, @hlcianfagna

Documentation: Add section about the new `\pager` command

---

crate/crash/command.py
crate/crash/commands.py
crate/crash/sysinfo.py
setup.py
tests/test_command.py
tests/test_commands.py
tests/test_sysinfo.py

Instead of vendoring `Version` from `packaging`, pull it in via shared library [`verlib2`](https://github.com/pyveci/verlib2).
`crash` broke after releasing `crate==0.35.0`, so I've yanked it again.
```python
ModuleNotFoundError: No module named 'crate.client._pep440'
```
-- https://github.com/crate/crash/actions/runs/7562783871/job/20593938496?pr=421#step:5:29
- https://github.com/crate/crate-python/pull/605
- https://github.com/crate/crate-python/pull/606

Use `verlib2.Version` instead of `crate.client._pep440.Version`

---

CHANGES.txt
crate/crash/command.py
docs/run.rst
tests/test_command.py

Coming from GH-370, this patch introduces the `--timeout` command-line argument to specify the (connect, read) timeout values. The default connect timeout is five seconds now, the default read timeout is infinite.
- Needs https://github.com/crate/crate-python/pull/603.

Add command-line argument `--timeout`, to configure network timeout values

---

CHANGES.txt
crate/crash/command.py

Better catch unauthorized errors with forced password prompt instead of displaying stack trace, when using the `-W` option.
```
% crash --hosts 'https://elite-krait.eks1.eu-west-1.aws.cratedb.net:4200' -U 'admin' -W
Password: 
401 Client Error: Unauthorized
```
Before, it was like:
<details>
```
Password:
Traceback (most recent call last):
File "/path/to/.venv/bin/crash", line 8, in <module>
sys.exit(main())
^^^^^^
File "/path/to/.venv/lib/python3.11/site-packages/crate/crash/command.py", line 589, in main
raise e
File "/path/to/.venv/lib/python3.11/site-packages/crate/crash/command.py", line 575, in main
cmd = _create_shell(crate_hosts, error_trace, output_writer, is_tty,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

better catch unauthorized errors with forced password prompt

---

LICENSE
README.rst
docs/appendices/compatibility.rst
docs/appendices/formats.rst
docs/getting-started.rst

Chore: Rename `crate.io` to `cratedb.com`

---

README.rst
docs/index.rst
docs/troubleshooting.rst

When connecting to CrateDB Cloud, you may observe connection errors when using `crash` on macOS. The reason is because Python may have skipped installing its SSL root certificate bundle on macOS. Thanks for reporting this, @simonprickett.
This patch adds a new troubleshooting section to the documentation, in order to educate users about how to improve the situation / resolve the issue.
https://crash--425.org.readthedocs.build/en/425/troubleshooting.html
[Issue connecting to CrateDB Cloud cluster from local machine](https://community.cratedb.com/t/issue-connecting-to-cratedb-cloud-cluster-from-local-machine/1707)
Please advise wording improvements as applicable.

Documentation: Add guidelines about debugging connectivity problems

---

CHANGES.txt
setup.py

It is needed to accompany the recent improvements about `--timeout`. Fixes `float() argument must be a string or a real number, not 'Timeout'`, when using a crate-python version which is not recent.
- GH-428

Update to crate>=0.35.2

---

.gitignore
CHANGES.txt
setup.py
tests/test_integration.py

Use "Testcontainers" as framework for providing service fixtures.
- GH-402
- https://github.com/crate-workbench/cratedb-toolkit/pull/82

Use testcontainers to improve platform coverage

---

CHANGES.txt
crate/crash/command.py
crate/crash/output.txt
tests/test_command.py
tests/test_commands.py
tests/util.py

When prefixing an SQL statement with an SQL comment (both per-line `--` and block `/* */`), crash mistreats that comment as an SQL command when printing its status line.
**Full Example:**
```sql
$ echo '/*foo*/ select 1' | crash
CONNECT OK
+---+
| 1 |
+---+
| 1 |
+---+
FOO 1 row in set (0.001 sec)
```
Because crash already uses the [sqlparse](https://pypi.org/project/sqlparse/) SQL parser, it wasn't too difficult to re-use its tokenizer already for extracting the proper canonical SQL command from the SQL expression.
```sql
$ echo '/*foo*/ select 1' | crash
CONNECT OK
+---+
| 1 |
+---+
| 1 |
+---+
SELECT 1 row in set (0.003 sec)
```
The [fundamental change](https://github.com/crate/crash/pull/432#pullrequestreview-1941195847) is very slim, but the patch grew a bit in size because software …

Fix status line display of the executed SQL command

---

crate/crash/command.py
tests/test_command.py

After recent improvements (GH-432), SQL command _arguments_ came through verbatim:
```sql
DENY DQL, DML, DDL, AL ON SCHEMA sys TO test;
DENY DQL, DML, DDL, AL OK, 1 row affected (0.082 sec)
```
This fixes it to just display the effective SQL command, without any arguments:
```sql
DENY OK, 1 row affected (0.082 sec)
```

Fix status line display of the executed SQL command, part 2

---

setup.py

This reverts commit f749cb2f97b5d443dc92dbb20b3d719f964d0f0c.
GH-435 was wrong, upgrading `pip` and `setuptools` instead is right.
- https://github.com/crate/jenkins-dsl/pull/1237

Revert "Fix dependencies for testing"

---

CHANGES.txt
crate/crash/command.py

Thanks for reporting, @romseygeek and @proddata.
- GH-438
After an improvement in crate-python 0.34, this error case is conveyed through `IntegrityError`. Beforehand, a more generic `ProgrammingError` was used.
Without the update, a duplicate key exception causes crash to exit prematurely and unexpectedly, when using more recent versions of crate-python.
Now, both exception types will be handled in the same way.

Fixed handling of `DuplicateKeyException` errors after crate-python 0.34

---

docs/conf.py
docs/requirements.txt

- Enable version chooser.
- Use most recent version of crate-docs-theme.
- https://crash--444.org.readthedocs.build/en/444/
- https://github.com/crate/crash/pull/445

Documentation: Enable version chooser [master]

---

docs/conf.py
docs/requirements.txt

- Enable version chooser.
- Use most recent version of crate-docs-theme.
- https://crash--445.org.readthedocs.build/en/445/
- https://github.com/crate/crash/pull/444

Documentation: Enable version chooser [0.31]

---

.github/workflows/main.yml

Use CrateDB 4.8.4, 5.9.2, and nightly.

CI: Update CrateDB test matrix versions

---

docs/getting-started.rst

This implements a suggestion to complete the documentation by educating users how to terminate SQL statements.
- GH-442
Thanks, @bmunkholm.

Documentation: Clarify how to terminate SQL statements

---

README.rst
docs/getting-started.rst

Installing Python packages using `pip`, eventually contaminating the system Python installation, has been deprecated by default. The recommended installation method, at least as advertised by Debian, is to use `pipx`.
```
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
```
- GH-443
Thanks, @bmunkholm.

Documentation: Advertise `pipx` for program installation (PEP 668)

---

setup.py

This reverts commit f717e7fbe66a8c4ea7de6576067e3c7cb9beb6fe.
- GH-453
After this patch, when installing the project into a fresh sandbox environment on my workstation, the test suite fails to discover the `crate.crash` module. I don't know why this doesn't happen on CI.

Revert "Python: Fix "implicit namespace packages" migration"

---

README.rst
docs/getting-started.rst

GH-451 wasn't correct: `pipx` does not understand `--upgrade`. It slipped in on a recent "improvement" to the docs.
- Report: [Installing crash with pipx fails](https://community.cratedb.com/t/installing-crash-with-pipx-fails/1922)

Documentation: Fix advertised `pipx` command

---

.github/workflows/main.yml

CI: Provide Python 3.7. EOL, it was removed from recent GHA runners

---

CHANGES.txt
setup.py

Validate and bring in an improvement to crate-python.
- https://github.com/crate/crate-python/pull/691
- https://github.com/crate/cratedb-toolkit/pull/349
- https://github.com/crate/sqlalchemy-cratedb/pull/195
- https://github.com/crate/stevedore/pull/325
- https://github.com/crate/cloud-api/pull/3038

Update to `crate-2.0.0`, which uses `orjson` for JSON marshalling

---

setup.py

The fundamental patch GH-459 needs a little update, pulling in a more recent pre-release version of crate-python.
- https://github.com/crate/crate-python/pull/691

Dependencies: Update to `crate>=2.0.0.dev6`, restoring JSON marshalling

---

docs/index.rst

Move down Github admonition (it's secondary) and make screenshots visible in size.
Keep only last screenshot as the other two just leads up to the third.
https://crash--467.org.readthedocs.build/en/467/

Update index.rst: Readable screenshot, move down GH reference

---

.github/workflows/docs.yml

It saves a few cycles on the linkchecker, both on GHA and on remote web servers.
- GH-469

CI: Stop building `docs` on `macos-latest`

---

docs/getting-started.rst
docs/run.rst

Page local toc's are redundant now that we have them automatically in the right side.

Remove page local toc
